export * from './getFeatured'
export * from './getCollectionProducts'
export * from './getOtherIcons'
export * from './getOtherPlaces'
export * from './getLabelProducts'
export * from './getProduct'
export * from './getProducts'
