name: Build

on:
  push:
    branches: [query]

jobs:
  BUILD:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build --stats-error-details
        env:
          FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          FIREBASE_MSG_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          FIREBASE_DB_URL: ${{ secrets.REACT_APP_DATEBASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_PUBLIC_ANON_KEY: ${{ secrets.SUPABASE_PUBLIC_ANON_KEY }}
      - uses: actions/upload-artifact@v1
        with:
          name: buildOutcome
          path: dist

  DEPLOY:
    needs: [BUILD]
    runs-on: [ubuntu-latest]
    steps:
      - run: git clone --branch master https://${{secrets.USERNAME}}:${{ secrets.TOKEN }}@github.com/${{secrets.USERNAME}}/${{secrets.REPO_NAME}}.git .
      - run: git config user.email ${{secrets.EMAIL}}
      - run: git config user.name ${{secrets.USERNAME}}
      - run: git remote set-url origin https://${{secrets.USERNAME}}:${{secrets.TOKEN}}@github.com/${{secrets.USERNAME}}/${{secrets.REPO_NAME}}.git
      - uses: actions/download-artifact@v1.0.0
        with:
          name: buildOutcome
          path: ./
      - run: git add .
      - run: git status
        id: status
      - run: git commit --allow-empty --message "${{ github.event.head_commit.message }}"
      - run: git push --set-upstream origin master
