name: Build

on:
  push:
    branches: [dev]

jobs:
  BUILD:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: npm install
      - run: npm run lint
      - run: npm run build --stats-error-details
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_PUBLIC_ANON_KEY: ${{ secrets.SUPABASE_PUBLIC_ANON_KEY }}
          MEASUREMENT_ID: ${{secrets.MEASUREMENT_ID}}
      - uses: actions/upload-artifact@v1
        with:
          name: buildOutcome
          path: dist

  LIGHTHOUSE:
    needs: [BUILD]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g @lhci/cli
      - uses: actions/download-artifact@v1.0.0
        with:
          name: buildOutcome
          path: ./
      - run: lhci autorun
      - run: dir
      - uses: actions/upload-artifact@v1
        with:
          name: lhci
          path: lhci

  DEPLOY:
    needs: [LIGHTHOUSE]
    runs-on: [ubuntu-latest]
    steps:
      - run: git clone --branch master https://${{secrets.USERNAME}}:${{ secrets.TOKEN }}@github.com/${{secrets.USERNAME}}/${{secrets.REPO_NAME}}.git .
      - run: git config user.email ${{secrets.EMAIL}}
      - run: git config user.name ${{secrets.USERNAME}}
      - run: git remote set-url origin https://${{secrets.USERNAME}}:${{secrets.TOKEN}}@github.com/${{secrets.USERNAME}}/${{secrets.REPO_NAME}}.git
      - uses: actions/download-artifact@v1.0.0
        with:
          name: buildOutcome
          path: ./
      - run: git add .
      - run: git status
        id: status
      - run: git commit --allow-empty --message "${{ github.event.head_commit.message }}"
      - run: git push --set-upstream origin master
